from app.schemas.auth import *
from app.schemas.borrower import *
from app.schemas.application import *
from app.schemas.consent import *
from app.schemas.data_source import *
from app.schemas.prediction import *
from app.schemas.explanation import *
from app.schemas.decision import *
from app.schemas.appeal import *
from app.schemas.report import *
from app.schemas.transaction import *
from app.schemas.audit import *
from app.schemas.ai import *
